INSERT INTO PERFILES (NOMBRE, DESCRIPCION) VALUES ('CUIDADOR', 'Persona que cuida a otra persona dependiente');

INSERT INTO PERSONAS (DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES ('58963322D', 'Xavi','el_amo', STR_TO_DATE( '04-11-1996', '%d-%m-%Y' ));

INSERT INTO PERSONAS (DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO) VALUES ('12345678A', 'Abu','el_amo', STR_TO_DATE( '04-11-1950', '%d-%m-%Y' ));

INSERT INTO CUIDADORES(ID_PERSONA) VALUES((SELECT ID FROM PERSONAS WHERE DNI = '58963322D'));

INSERT INTO USUARIOS (USERNAME, PASSWORD, ID_CUIDADOR,ID_PERFIL) VALUES ('skaterpro360', 'nomirar',(SELECT ID FROM CUIDADORES WHERE ID_PERSONA = (SELECT ID FROM PERSONAS WHERE DNI = '58963322D')),(SELECT ID FROM PERFILES WHERE NOMBRE = 'CUIDADOR'));

INSERT INTO DEPENDIENTES (ALIAS, ID_PERSONA, ID_CUIDADOR) Values ('abu',(SELECT ID FROM PERSONAS WHERE DNI = '12345678A'),(SELECT ID FROM CUIDADORES WHERE ID_PERSONA = (SELECT ID FROM PERSONAS WHERE DNI = '58963322D')));

INSERT INTO SPDS VALUES ();

INSERT INTO TRATAMIENTOS (ID_DEPENDIENTE, ID_SPD) VALUES ((SELECT ID FROM DEPENDIENTES WHERE ALIAS = 'abu'),1);

INSERT INTO MEDICAMENTOS (NOMBRE) VALUES ('LSD');

INSERT INTO CARGAS (ID_SPD, ID_MEDICAMENTO, CANTIDAD) VALUES (1,(SELECT ID FROM MEDICAMENTOS WHERE NOMBRE = 'LSD'),3);

INSERT INTO DOSIS (HORA_INICIO, VECES_POR_DIA, ID_MEDICAMENTO, ID_TRATAMIENTO) VALUES (TIME("12:00:00"), 5, (SELECT ID FROM MEDICAMENTOS WHERE NOMBRE = 'LSD'), 1);
